export const actions = {
	"update_device": { "type": "device", "deviceType": true },
	"update_device_queued": { "type": "device", "deviceType": true },
	"create_device": { "type": "device", "deviceType": true },
	"add_model_notes": { "type": "note", "deviceType": false },
	"update_model_note_visibility": { "type": "note", "deviceType": false },
	"delete_device_note": { "type": "note", "deviceType": false },
	"move_device": { "type": "device", "deviceType": true },
	"restart_device": { "type": "device", "deviceType": true },
	"reset_device_data": { "type": "device", "deviceType": true },
	"delete_device": { "type": "device", "deviceType": true },
	"push_device_fw": { "type": "device", "deviceType": true },
	"receive_device_shipment": { "type": "device", "deviceType": true },
	"check_shipment_quality": { "type": "device", "deviceType": true },
	"ship_out_device": { "type": "device", "deviceType": true },
	"create_order": { "type": "device", "deviceType": true },
	"edit_order": { "type": "device", "deviceType": true },
	"update_shipping_info": { "type": "device", "deviceType": true },
	"user_login": { "type": "user", "deviceType": false },
	"add_user": { "type": "user", "deviceType": false },
	"edit_user": { "type": "user", "deviceType": false },
	"delete_user": { "type": "user", "deviceType": false },
	"change_user_password": { "type": "user", "deviceType": false },
	"order_add_attachment": { "type": "device", "deviceType": true },
	"order_delete_attachment": { "type": "device", "deviceType": true },
	"update_cm_fw_versions": { "type": "device", "deviceType": true },
};
