export enum AccessFunctions {
	super_admin = 'super_admin',
	management_function = 'management_function',
	admin = 'admin',
	client = 'client',
	cm = 'cm',
}

export const pagesAccessFunctions = {
	'user_list': [AccessFunctions.admin],
	'user_create': [AccessFunctions.admin],
	'user_edit': [AccessFunctions.admin],
	'user_access_functions': [AccessFunctions.management_function],
	'api_logs': [AccessFunctions.admin, AccessFunctions.cm],
	'action_log': [AccessFunctions.admin],
	'system_info': [AccessFunctions.admin, AccessFunctions.cm],
	'dashboard': [AccessFunctions.admin, AccessFunctions.cm, AccessFunctions.management_function],
	'shipment_quality_history': [AccessFunctions.admin, AccessFunctions.cm],
	'shipping_out': [AccessFunctions.admin, AccessFunctions.cm],
	'shipping_out_history': [AccessFunctions.admin, AccessFunctions.cm],
	'receive_shipment_results': [AccessFunctions.admin, AccessFunctions.cm],
	'shipment_quality_results': [AccessFunctions.admin, AccessFunctions.cm],
	'cellular_info_track': [AccessFunctions.admin, AccessFunctions.cm],
	'orders_management': [AccessFunctions.admin],
	'create_order': [AccessFunctions.admin],
	'view_order': [AccessFunctions.admin],
	'edit_order': [AccessFunctions.admin],
	'firmware_update': [AccessFunctions.admin],
	'user_roles': [AccessFunctions.management_function],
	'cm_fw_versions': [AccessFunctions.admin]
};


export const accessFunctionsObj = {
	'user_list': {controlledBy: 'management_function'},
	'user_create': {controlledBy: 'management_function'},
	'user_edit': {controlledBy: 'management_function'},
	'user_access_functions': {controlledBy: 'management_function'},
	'api_logs': {controlledBy: 'management_function'},
	'fw_upload': {controlledBy: 'management_function'},
	'fw_logs': {controlledBy: 'management_function'},
	'action_log': {controlledBy: 'management_function'},
	'device_list': {controlledBy: 'management_function'},
	'device_create': {controlledBy: 'management_function'},
	'device_settings': {controlledBy: 'management_function'},
	'device_events': {controlledBy: 'management_function'},
	'device_define': {controlledBy: 'management_function'},
	'system_info': {controlledBy: 'management_function'},
	'cell_info': {controlledBy: 'management_function'},
	'debug_records': {controlledBy: 'management_function'},
	'connectivity_track': {controlledBy: 'management_function'},
	'config_track': {controlledBy: 'management_function'},
	'device_page': {controlledBy: 'management_function'},
	'dashboard': {controlledBy: 'management_function'},
	'search_device_details': {controlledBy: 'management_function'},
	'device_notes': {controlledBy: 'management_function'},
	'rejection_devices_logs': {controlledBy: 'management_function'},
	'receive_shipment': {controlledBy: 'management_function'},
	'shipment_quality': {controlledBy: 'management_function'},
	'receive_shipment_history': {controlledBy: 'management_function'},
	'shipment_quality_history': {controlledBy: 'management_function'},
	'shipping_out': {controlledBy: 'management_function'},
	'shipping_out_history': {controlledBy: 'management_function'},
	'receive_shipment_results': {controlledBy: 'management_function'},
	'shipment_quality_results': {controlledBy: 'management_function'},
	'cellular_info_track': {controlledBy: 'management_function'},
	'orders_management': {controlledBy: 'management_function'},
	'create_order': {controlledBy: 'management_function'},
	'view_order': {controlledBy: 'management_function'},
	'edit_order': {controlledBy: 'management_function'},
	'firmware_update': {controlledBy: 'management_function'},
	'user_roles': {controlledBy: 'management_function'},
	'cm_fw_versions': {controlledBy: 'management_function'},
}